model: OSEMBE
scenario: DIAG-NPI
region: ['Austria', 'Belgium', 'Bulgaria', 'Switzerland', 'Cyprus', 'Czech Republic', 'Germany', 'Denmark', 'Estonia', 'Spain', 'Finland', 'France', 'Greece', 'Croatia', 'Hungary', 'Ireland', 'Italy', 'Lithuania', 'Luxembourg', 'Latvia', 'Malta', 'The Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Sweden', 'Slovenia', 'Slovakia', 'United Kingdom',]
results:
- iamc_variable: 'Capacity|Electricity'
  capacity: ['^((?!(EL)|(00)).)*$']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Biomass'
  capacity: ['(?=^.{2}(BF))^((?!00).)*$','(?=^.{2}(BM))^((?!00).)*$', '(?=^.{2}(WS))^((?!00).)*$']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Coal'
  capacity: ['(?=^.{2}(CO))^((?!00).)*$']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Gas'
  capacity: ['(?=^.{2}(NG))^((?!00).)*$']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Geothermal'
  capacity: ['(?=^.{2}(GO))^((?!00).)*$']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Hydro'
  capacity: ['^.{2}(HY)']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Nuclear'
  capacity: ['^.{2}(NU)']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Ocean'
  capacity: ['^.{2}(OC)']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Oil'
  capacity: ['(?=^.{2}(HF))^((?!00).)*$']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Solar|PV'
  capacity: ['^.{2}(SO)']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Wind|Offshore'
  capacity: ['(?=^.{2}(WI))^.{4}(OF)']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Capacity|Electricity|Wind|Onshore'
  capacity: ['(?=^.{2}(WI))^.{4}(ON)']
  unit: GW
  osemosys_param: TotalCapacityAnnual
- iamc_variable: 'Emissions|CO2|Energy|Supply|Electricity'
  emission: [CO2]
  unit: ktCO2/yr
  osemosys_param: AnnualTechnologyEmission
#- iamc_variable: "Emissions|PM2.5"
#  emission: ["**PM25"]
#  unit: ktCO2/yr
#  osemosys_param: AnnualTechnologyEmission
- iamc_variable: 'Final Energy'
  demand: [E2]
  unit: PJ/yr
  osemosys_param: Demand
- iamc_variable: 'Primary Energy'
  primary_technology: ['^.{6}(I0)','^.{6}(X0)','^.{2}(HY)','^.{2}(OC)','^.{2}(SO)','^.{2}(WI)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Biomass|Electricity'
  primary_technology: ['(?=^.{2}(BM))^.{4}(00)','(?=^.{2}(WS))^.{4}(00)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Coal|Electricity'
  primary_technology: ['(?=^.{2}(CO))^.{4}(00)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Gas|Electricity'
  primary_technology: ['(?=^.{2}(NG))^.{4}(00)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Geothermal'
  primary_technology: ['(?=^.{2}(GO))^.{4}(00)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Hydro'
  primary_technology: ['^.{2}(HY)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Nuclear'
  primary_technology: ['^.{2}(UR)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Ocean'
  primary_technology: ['^.{2}(OC)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Oil'
  primary_technology: ['(?=^.{2}(OI))^.{4}(00)','(?=^.{2}(HF))^.{4}(00)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Solar'
  primary_technology: ['^.{2}(SO)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual
- iamc_variable: 'Primary Energy|Wind'
  primary_technology: ['^.{2}(WI)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual