model: OSEMBE
scenario: Reference
results:
- iamc_variable: 'Emissions|CO2|Energy|Supply|Electricity'
  emission: [CO2]
  unit: ktCO2/yr
  osemosys_param: AnnualTechnologyEmission
- iamc_variable: "Emissions|PM2.5"
  emission: ["**PM25"]
  unit: ktCO2/yr
  osemosys_param: AnnualTechnologyEmission
- iamc_variable: 'Primary Energy'
  primary_technology: [****00I00,****00X00,**HY*****,**OC*****,**SO*****,**WI*****]
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual