model: OSEMBE
scenario: Reference
results:
- iamc_variable: 'Emissions|CO2|Energy|Supply|Electricity'
  emission: [CO2]
  unit: ktCO2/yr
  osemosys_param: AnnualTechnologyEmission
- iamc_variable: "Emissions|PM2.5"
  emission: ["**PM25"]
  unit: ktCO2/yr
  osemosys_param: AnnualTechnologyEmission
- iamc_variable: 'Primary Energy'
  primary_technology: ['^.{6}(I0)','^.{6}(X0)','^.{2}(HY)','^.{2}(OC)','^.{2}(SO)','^.{2}(WI)']
  unit: PJ/yr
  osemosys_param: ProductionByTechnologyAnnual